# Generated by Django 4.1.2 on 2022-10-19 18:40

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_news_slug_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('জাতীয়', 'জাতীয়'), ('আন্তর্জাতিক', 'আন্তর্জাতিক'), ('বিনোদন', 'বিনোদন'), ('খেলা', 'খেলা')], max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 18, 40, 1, 985339, tzinfo=datetime.timezone.utc)),
        ),
    ]
