# Generated by Django 4.1.2 on 2022-10-20 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_adds_name_alter_news_category_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 15, 45, 23, 907324, tzinfo=datetime.timezone.utc)),
        ),
    ]
